GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/64b7f98cf6f694408bfd3386

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "John Smith",
  "number": "123-456-7890"
}